name: kwale
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.1.0
  intl_phone_number_input: ^0.7.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.1
  url_launcher: ^6.1.12
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  fluttertoast: ^8.2.2
  mailer: ^6.0.1 #email verification
  email_validator: ^2.1.17 #validate email
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.1.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  share_plus: ^7.1.0
  path_provider: ^2.1.0
  flare_flutter: ^3.0.2
  custom_refresh_indicator: ^2.2.1
  toggle_switch: ^2.1.0
  search_choices: ^2.2.7
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "assets/images/logo/Kwale-logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo/Kwale-logo_foreground.png"
  web:
    generate: true
    image_path: "assets/images/logo/Kwale-logo.png"

# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/login_images/
    - assets/images/featured_images/
    - assets/images/profile/
    - assets/images/card_images/
    - assets/images/order_confirmed/
    - assets/images/category_images/
    - assets/images/logo/
    - assets/images/nav_bar_icons/
    - assets/images/slider_images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
